### ISSUE TITLE
installation instructions error in the README file

### ISSUE THREAD

**Issue by felipebm** [madsdk/yasnippets-latex#9]
The first paragraph of the Instructions section states:

> "Once that is done installation is done by simply copying the files .yas-parents, .yas-ignore-filenames-as-triggers, .yas-parents, and the snippets into the 'snippets/latex-mode' subdirectory within your YASnippet installation."

As you can see _.yas-parents_ is repeated, and I believe it should be the _.yas-make-groups_ file as it is done in the _install.sh_ script .

Thanks for the snippets!

**Comment by zpxing** [comment]
Dear Doris,

Would you please to make clear copies of my diploma and trafic information,
then send them to me by email A.S.A.P? I need them to ask for help from one
of my friends. Thank you.

On 6 February 2014 23:58, felipebm notifications@github.com wrote:

> The first paragraph of the Instructions section states:
> 
> "Once that is done installation is done by simply copying the files
> .yas-parents, .yas-ignore-filenames-as-triggers, .yas-parents, and the
> snippets into the 'snippets/latex-mode' subdirectory within your YASnippet
> installation."
> 
> As you can see _.yas-parents_ is repeated, and I believe it should be the
> _.yas-make-groups_ file as it is done in the _install.sh_ script .
> 
> Thanks for the snippets!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/madsdk/yasnippets-latex/issues/9
> .

## 

Regards,

Zhaopeng Xing

**Comment by felipebm** [comment]
?????

**Comment by madsdk** [comment]
felipebm: Thank you for pointing that out to me. It's fixed now. It seems we got some Github spam as well? :)
